[IV-21-22] Completar objetivo 2
Balrrach/IV-Proyecto pull request #14
Opened 2021-10-09 10:01 UTC by Asmilex

He incluido commits correspondientes al PR #12, y no sé cuál es la forma más correcta de ignorar esos archivos. Creo que primero se debería resolver ese PR, y después tratar éste. Sin embargo, prefiero dejar este PR abierto para trabajar de forma más cómoda. 

Este PR cerraría el issue #13, y avanzaría los #5, #3 y #2.

Se ha elegido Typescript por lo versátil que es el lenguaje. Es cómodo de escribir, tiene las ventajas de la portabilidad de Javascript y la robustez del tipado fuerte. Además, es uno de los lenguajes sugeridos por el Product Manager.

2021-10-14 07:44 UTC, Balrrach requested changes
Bien en general. Introducir localizaciones en lugar de los restaurantes.

2021-10-14 07:44 UTC, Balrrach commented on src/classes/mapa.ts
> +}
Lo ideal es que el mapa contenga localizaciones puesto que los clientes pueden estar en ubicaciones distintas de los restaurantes y supone una abstracción sana y nada costosa.
Para implementarlo puedes hacer una clase locaclización y puedes componer la clase restaurante con esta.

2021-10-14 07:44 UTC, Balrrach commented on src/classes/pedido.ts
> +  destino: Restaurante = new Restaurante();
Teniendo en cuenta el cambio propuesto el destino debe de ser una ubicación.

2021-10-14 07:44 UTC, Balrrach commented on src/classes/ruta.ts
> +  destinos: Restaurante[] = [];
Igualmente la ruta funciona en términos de localizaciones.

2021-10-14 07:47 UTC, Asmilex commented on src/classes/mapa.ts
> +}
Resuelto en 5827829

2021-10-14 07:47 UTC, Asmilex commented on src/classes/pedido.ts
> +  destino: Restaurante = new Restaurante();
Resuelto en 5827829

2021-10-14 08:04 UTC, Balrrach requested changes

2021-10-14 08:04 UTC, Balrrach commented on src/classes/localizacion.ts
>    recibir(pedido: Pedido) {}
Estaría bien un método preparar pedido ya que el restaurante, en la vida real no tiene listo el pedido al instante, tiene que cocinar la comida.

2021-10-14 08:04 UTC, Balrrach commented on src/classes/mapa.ts
>    localizaciones: Restaurante[] = [];
Es un array de localizaciones

2021-10-14 08:10 UTC, Asmilex commented on src/classes/localizacion.ts
> +  ID = 0;
Quizás no sea necesario, pues las coordenadas actuarían como identificador (al menos, de forma física).

Arreglado en 17c716c.

2021-10-14 08:10 UTC, Asmilex commented on src/classes/mapa.ts
>    localizaciones: Restaurante[] = [];
Arreglado en 01071a7

2021-10-14 08:21 UTC, Balrrach commented on src/classes/localizacion.ts
>    recibir(pedido: Pedido) {}
Hay que hacer un método para entregar el pedido al repartidor.
Hay que mover el método recibir pedido a la clase localización.

2021-10-15 17:17 UTC, JJ commented on src/classes/localizacion.ts
> +  nombre = '';
¿No tiene tipo este probetico?

2021-10-15 17:20 UTC, JJ approved these changes
Como PMV está bien, y muy bien currado, incluso más de lo que se pedía... Pero ya puestos podías haber hecho el recorrido completo. Especialmente, con tipos.
Por otro lado, no tienes por ningún lado que se cierre el issue correspondiente. Añade las palabras clave para que se cierre al mergear.

2021-10-15 17:20 UTC, JJ commented on src/classes/pedido.ts
> +  ID = 0;
Aparte de que no tiene tipo, no sé como lo vas a generar, pero si vas a hacerlo en serio igual sería conveniente que declararas una variable de clase. Eso tendrías que especificarlo en el issue correspondiente.

2021-10-15 17:20 UTC, JJ commented on src/classes/producto.ts
> +  ID = -1;
Igual, declara tipos. TS tiene tipado gradual, pero si usas los tipos úsalos siempre.

2021-10-15 17:20 UTC, JJ commented on src/classes/ruta.ts
> +    // FIXME temporal
:sob:

2021-10-16 10:05 UTC, Asmilex commented on src/classes/ruta.ts
> +    // FIXME temporal
Typescript se queja si no devuelvo nada, así que mando un restaurante vacío :(

2021-10-16 10:25 UTC, JJ commented on src/classes/ruta.ts
> +    // FIXME temporal
Es por el comentario.

2021-10-16 14:28 UTC, Asmilex commented on src/classes/ruta.ts
> +    // FIXME temporal
Me gusta usar anotaciones estilo TODO, FIXME y similares. Tengo una extensión que me los resalta :)

2021-10-17 06:55 UTC, JJ commented on src/classes/ruta.ts
> +    // FIXME temporal
Los comentarios no son para eso. Abre un issue. Nunca se programa para uno, se programa para el cliente y luego le equipo. Finalmente para uno, claro.

2021-10-17 14:37 UTC, merged