Actualizo la Descripcion del Problema
Balrrach/IV-Proyecto pull request #7
Opened 2021-09-25 16:44 UTC by Balrrach

2021-09-25 18:59 UTC, JJ requested changes
Por favor, documenta los roles en un documento aparte, como se te indica en el guión. 
Cuida los errores tipográficos, pone "portotipo". Este hito corresponde a un producto, el resto no.
En particular, no parece razonable que el primer producto sea un prototipo.

2021-09-25 18:59 UTC, JJ commented on README.md
>  Las restricciones son las siguientes:
Corrige las restricciones. Repites "entregar"

2021-09-25 19:12 UTC, Balrrach commented on README.md
>  Las restricciones son las siguientes:
Disculpe los errores ortográficos, las prisas son muy malas, ya están corregidos.
Con respecto a los perfiles, entendí que los propios perfiles emitían peticiones que serán los casos de uso y que estas dos cosas han de aparecer en el mismo issue. ¿Tengo que indicar los roles en un documento diferente y luego hacer referencia dichos roles en las HU(issues)?, ¿o las HU están desligados de los perfiles de los usuarios?. No entiendo esto muy bien a partir de las instrucciones que figuran en el guion.

2021-09-26 07:11 UTC, JJ commented on README.md
>  Las restricciones son las siguientes:
Efectivamente, eso es lo que dijimos en clase. Los issues son sólo para HUs atómicas, no para perfiles. ¿Cómo van a estar desligadas las HUs de los perfiles de usuario? Cada HU tiene es de uno (o varios) perfiles de usuario.

2021-09-26 15:40 UTC, JJ commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
¿Seguro que no hay ningún hito antes de la aplicación operativa? ¿Qué significa para ti un producto mínimamente viable?

2021-09-26 16:30 UTC, Balrrach commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
Entiendo que es un producto que sólo realiza las funciones fundamentales para las que fue diseñado sin incluir características extra y que tiene una interfaz rudimentaria. Lo mínimo e imprescindible como para probar el correcto funcionamiento de la aplicación base. Por esto entiendo que debe ser el primer hito.

2021-09-26 16:34 UTC, JJ commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
Lo que pienso ya te lo he dicho.
Los hitos tienen que corresponder de forma realista a lo que vayas a hacer durante la asignatura. Durante la asignatura no vamos a ver nada de UI. ¿No vas a alcanzar ni siquiera el primer hito?
Por otro lado, sirven para organizarte tú el trabajo. ¿Vas a desarrollar el "mínimo UI" y el backend simultáneamente? ¿No recuerdas el ejemplo que di en clase, precisamente con esto?
REvisa por favor el concepto de producto mínimamente viable, que puede incluir releases internos, y del cual dimos en clase varios ejemplos.

2021-09-26 16:48 UTC, Balrrach commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
No entiendo que problema hay en que el "mínimo UI" sea la propia terminal y que la aplicación dé opciones entra las que el usuario pueda escoger. Un producto así es funcional y permite centrar el desarrollo en el backend. No le veo el sentido a un hito anterior a este. ¿Quizás el término producto mínimamente viable no sea el correcto y me estoy expresando mal?.

2021-09-26 18:08 UTC, JJ commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
Por favor, consulta el concepto de mínimamente viable y recuerda lo que hemos dicho en la clase dividida. TL;DR: para que el "usuario" "escoja opciones" habrá antes que hacer una serie de productos. Si no tienes esos productos, el usuario no podrá escoger ninguna opción.

2021-09-26 21:27 UTC, Balrrach commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
Claro, entiendo que la elaboración de las opciones(productos) es parte del primer milestone. No me cuesta escindir el primer milestone en dos: uno primero en el que se desarrolle el backend y uno segundo en el que se desarrollen los producos. Otra opción es escribirlos como issues que formen parte del primer milestone.

2021-09-27 16:44 UTC, JJ commented on docs/Roadmap.md
> +| [Aplicación Operativa](https://github.com/Balrrach/IV-Proyecto/milestone/1)	| Primera versión funcional. Cumplirá con los requisitos básicos. | En desarrollo | Restringido |
Los issues corresponderán siempre a una historia de usuario y un milestone. A partir de ahí, haz lo que consideres conveniente.

2021-10-01 11:55 UTC, Balrrach commented
Añadidos issues asociados a la resolución del problema inicial junto con su correspondiente milestone.

2021-10-01 15:26 UTC, JJ requested changes
Me temo que nos queda un poco todavía, aunque hemos avanzado.
1. Los hitos no son productos mínimamente viables, ni están descritos como tales
2. El hito 0 va a programar el algoritmo, ¿sobre qué clases? ¿Vas a programar el algoritmo y ya está?

2021-10-02 07:19 UTC, JJ commented
Adicionalmente, no entiendo muy bien la numeración de los hitos. ¿Por qué el .1?
¿Por qué el que debería ser el hito 1 no tiene ninguna HU? ¿Cómo se va a empezar a trabajar con él?
Al menos ese hito sí está definido como un PMV, un "módulo". Pero tendrías que dotarle con algún tipo de contenido para que se pudiera trabajar con él. Asígnale alguna de las HUs que eventualmente necesiten las estructuras de datos, luego lo puedes cambiar (los issues se quedarán)
Tienes más hitos de la cuenta. Los hitos son una hoja de ruta para empezar a trabajar. Más alla de dos o tres, es difícil que necesites tantos. Luego se van elaborando sobre la marcha. REcuerda, no es waterfall, no se escribe un montón antes de empezar a trabajar. Los hitos externos no creo que puedan llegar hasta muy avanzado. El 1.2 no tiene mucho sentido. 
En resumen, para alcanzar este objetivo tienes que reorganizar un poco los hitos (el 1 y dos sí tienen productos mínimamente viables) pero, lo más importante, meter algún contenido de HUs en esos hitos porque si no es imposible desarrollar.

2021-10-02 07:22 UTC, JJ commented
Por otro lado, el objetivo 2 de este proyecto lo llevará a cabo @jesusmarzor

2021-10-02 08:44 UTC, JJ commented
> Adicionalmente, no entiendo muy bien la numeración de los hitos. ¿Por qué el .1? ¿Por qué el que debería ser el hito 1 no tiene ninguna HU? ¿Cómo se va a empezar a trabajar con él? Al menos ese hito sí está definido como un PMV, un "módulo". Pero tendrías que dotarle con algún tipo de contenido para que se pudiera trabajar con él. Asígnale alguna de las HUs que eventualmente necesiten las estructuras de datos, luego lo puedes cambiar (los issues se quedarán) Tienes más hitos de la cuenta. Los hitos son una hoja de ruta para empezar a trabajar. Más alla de dos o tres, es difícil que necesites tantos. Luego se van elaborando sobre la marcha. REcuerda, no es waterfall, no se escribe un montón antes de empezar a trabajar. Los hitos externos no creo que puedan llegar hasta muy avanzado. El 1.2 no tiene mucho sentido. En resumen, para alcanzar este objetivo tienes que reorganizar un poco los hitos (el 1 y dos sí tienen productos mínimamente viables) pero, lo más importante, meter algún contenido de HUs en esos hitos porque si no es imposible desarrollar.

¿Qué partes de esto que he escrito no entiendes? En concreto, lo que te estoy diciendo aquí no es que no hayas puesto productos mínimamente viables. Es que no los has ordenado correctamente ni precisas qué contendrán esos productos, puesto que no hay ninguna HU asignada inicialmente a ellos.

2021-10-02 16:23 UTC, Asmilex commented
He estado echándole un vistazo al repositorio, y también considero que la estructura actual es algo problemática. 

Creo que los milestones están organizados como si fueran subtareas de cada milestone respectivo. Y de ahí la nomenclatura actual que tiene. Creo que vendría bien reconsiderar cuáles son las tareas más importantes de cada etapa de desarrollo, y replantear lo que debemos hacer para cada una. 

Además, creo que las user stories deberían modificarse para adaptar este cambio. Creo que el orden de algunas de ellas es incorrecto, pues tienen prioridad alguna de las más tardías. Comentaré en cada una de ellas mis impresiones. 

Por otra parte, he estado estudiando algunas soluciones para el problema. Creo que no resulta especialmente complicado, pero hay un par de detalles que debemos afinar. Quizás sea más adecuado esperar a arreglar los problemas del objetivo 1, y luego comentar esto. 

En mi opinión, las etapas deberían contener lo siguiente más o menos: 
- Primera: 
  - Estructuras básicas. 
  - Ser capaz de asociar nuevos pedidos a alguna localización, con un determinado destino. 
  - Algoritmo para calcular una ruta en función de varios parámetros (distancia entre nodos y/o tiempo necesario para tomar un camino; pedidos cargados actualmente), y que devuelva una ruta. 
- Segunda:
  - Repartidor toma pedidos y navega por la ruta. Consecuencias de esto. 
  - Estimación del tiempo restante. 
  - Pedidos con tiempo restante asociado. 
- Tercera: 
  - Sistema de pagos y cambio. Considero que esto es lo menos importante del problema, y solo es una capa que añadir por encima una vez se tenga todo.  

Esto sería más o menos cómo lo plantearía yo, viendo el problema y la documentación asociada en conjunto.

2021-10-02 16:43 UTC, JJ commented
De hecho, el objetivo 2 no requiere nada que vaya más allá de las estructuras básicas. Muchas gracias, @asmilex, :clap: :clap:

2021-10-02 21:11 UTC, Balrrach commented
> Adicionalmente, no entiendo muy bien la numeración de los hitos. ¿Por qué el .1?

Porque entiendo que el trabajo se va a dividir en diferentes hitos que van a estar todos ellos relacionados con la misma historia de usuario. Un primer hito será la la definición de la estructura, uno segundo la implementación, etc... Si no utilizo esta nomenclatura, al no conocer el numero de hitos necesarios para dicha HU Necesitaría reenumerar todos ellos cada vez que precise otro hito para dicha HU. 

> ¿Por qué el que debería ser el hito 1 no tiene ninguna HU? ¿Cómo se va a empezar a trabajar con él?

El primer hito constituye la base de la aplicación a desarrollar, como voy a asociarle una HU, no tiene ningún sentido, el problema a resolver lo estipula la empresa y los detalles los consulta con los clientes. La empresa no va al cliente y le pregunta: ¿que problema quiere que le resolvamos?.

> Al menos ese hito sí está definido como un PMV, un "módulo". Pero tendrías que dotarle con algún tipo de contenido para que se pudiera trabajar con él. Asígnale alguna de las HUs que eventualmente necesiten las estructuras de datos, luego lo puedes cambiar (los issues se quedarán).

Esto sinceramente no lo comprendo. Ya le he comentado que no se que HU se le puede asociar a dicho hito.

> Tienes más hitos de la cuenta. Los hitos son una hoja de ruta para empezar a trabajar. Más alla de dos o tres, es difícil que necesites tantos. Luego se van elaborando sobre la marcha. REcuerda, no es waterfall, no se escribe un montón antes de empezar a trabajar. Los hitos externos no creo que puedan llegar hasta muy avanzado.

Lo he estructurado de esta forma, con muchos hitos porque tras ver el seminario de PMV por segunda vez entendí que esta era la mejor forma de hacerlo puesto que cada HU se despliega en varios milestones entre los que figuran estructura e implementación entre otros. Lo único que he hecho es crear estos hitos para cada una de las "versiones" que consideré a partir de los issues.

Como le digo tengo problemas entendiendo esto y no quiero dar más palos de ciego hasta que me quede todo claro.

2021-10-02 21:17 UTC, Balrrach commented
> He estado echándole un vistazo al repositorio, y también considero que la estructura actual es algo problemática.
> 
> Creo que los milestones están organizados como si fueran subtareas de cada milestone respectivo. Y de ahí la nomenclatura actual que tiene. Creo que vendría bien reconsiderar cuáles son las tareas más importantes de cada etapa de desarrollo, y replantear lo que debemos hacer para cada una.

Sí, tengo que revisarlos.
 
> Además, creo que las user stories deberían modificarse para adaptar este cambio. Creo que el orden de algunas de ellas es incorrecto, pues tienen prioridad alguna de las más tardías. Comentaré en cada una de ellas mis impresiones.

He respondido a cada una de ellas.

> Por otra parte, he estado estudiando algunas soluciones para el problema. Creo que no resulta especialmente complicado, pero hay un par de detalles que debemos afinar. Quizás sea más adecuado esperar a arreglar los problemas del objetivo 1, y luego comentar esto.

Estoy de acuerdo.

> En mi opinión, las etapas deberían contener lo siguiente más o menos:
> 
>     * Primera:
>       
>       * Estructuras básicas.
>       * Ser capaz de asociar nuevos pedidos a alguna localización, con un determinado destino.
>       * Algoritmo para calcular una ruta en función de varios parámetros (distancia entre nodos y/o tiempo necesario para tomar un camino; pedidos cargados actualmente), y que devuelva una ruta.
> 
>     * Segunda:
>       
>       * Repartidor toma pedidos y navega por la ruta. Consecuencias de esto.
>       * Estimación del tiempo restante.
>       * Pedidos con tiempo restante asociado.
> 
>     * Tercera:
>       
>       * Sistema de pagos y cambio. Considero que esto es lo menos importante del problema, y solo es una capa que añadir por encima una vez se tenga todo.
> 
> 
> Esto sería más o menos cómo lo plantearía yo, viendo el problema y la documentación asociada en conjunto.

Estoy de acuerdo con la estructura que propones, es más o menos la que tenía en mente. En cuanto pueda revisaré los issues y los milestones para tratar de darle la estructura correcta al proyecto. ¡Gracias por las sugerencias!

2021-10-03 06:53 UTC, JJ commented
> > Adicionalmente, no entiendo muy bien la numeración de los hitos. ¿Por qué el .1?
> 
> Porque entiendo que el trabajo se va a dividir en diferentes hitos que van a estar todos ellos relacionados con la misma historia de usuario. Un primer hito será la la definición de la estructura, uno segundo la implementación, etc... Si no utilizo esta nomenclatura, al no conocer el numero de hitos necesarios para dicha HU Necesitaría reenumerar todos ellos cada vez que precise otro hito para dicha HU.

Me temo que no es así. Los hitos no tienen subhitos. Además, la estructura que has creado, con el .1 interno y el .2, que tendría que ir a continuación, externo, tampoco corresponde a un orden en el cual los más complejos siguen a los más simples. Los que sean externos irán siempre al final. Mi consejo es que, para superar este objetivo, simplemente elimines los externos.
> 
> > ¿Por qué el que debería ser el hito 1 no tiene ninguna HU? ¿Cómo se va a empezar a trabajar con él?
> 
> El primer hito constituye la base de la aplicación a desarrollar, como voy a asociarle una HU, no tiene ningún sentido, el problema a resolver lo estipula la empresa y los detalles los consulta con los clientes. La empresa no va al cliente y le pregunta: ¿que problema quiere que le resolvamos?.

Debes entender que la aplicación se hace en base a las historias de usuario. Son las historias de usuario las que conducen a pensar en la base de la aplicación, a través de issues intermedios. Los HUs pueden cambiar de hito, pero los issues que se saquen de ellos no. En todo caso, el equipo de desarrollo en la persona de @Asmilex te ha sugerido una estructura que le puede ayudar a comenzar a programar. Te animo a que sigas sus sugerencias para superar este hito.
> 
> > Al menos ese hito sí está definido como un PMV, un "módulo". Pero tendrías que dotarle con algún tipo de contenido para que se pudiera trabajar con él. Asígnale alguna de las HUs que eventualmente necesiten las estructuras de datos, luego lo puedes cambiar (los issues se quedarán).
> 
> Esto sinceramente no lo comprendo. Ya le he comentado que no se que HU se le puede asociar a dicho hito.

El hito es un PMV porque es un módulo, pero los productos mínimamente viables se tienen que describir y decir qué hacen para que el *product owner* (tú) pueda discernir si lo que le entrega el equipo de desarrollo es lo que él ha definido y lo que necesita el cliente. Y si no entiendes que los milestones/PMVs son una forma de organizar el desarrollo, y que las HUs son las que guían el desarrollo, por favor, revisa el concepto de las mismas, o, una vez más, escucha la sugerencia del equipo de desarrollo arriba para poder comenzar a organizar el mismo.
> 

> > Tienes más hitos de la cuenta. Los hitos son una hoja de ruta para empezar a trabajar. Más alla de dos o tres, es difícil que necesites tantos. Luego se van elaborando sobre la marcha. REcuerda, no es waterfall, no se escribe un montón antes de empezar a trabajar. Los hitos externos no creo que puedan llegar hasta muy avanzado.
> 
> Lo he estructurado de esta forma, con muchos hitos porque tras ver el seminario de PMV por segunda vez entendí que esta era la mejor forma de hacerlo puesto que cada HU se despliega en varios milestones entre los que figuran estructura e implementación entre otros. Lo único que he hecho es crear estos hitos para cada una de las "versiones" que consideré a partir de los issues.

Por favor, entiende lo de arriba como sugerencias para superar el hito. Si quieres entenderlo como un punto de discusión, estaré encantado de hablarlo contigo en el momento que sea necesario. Pero si tratas de justificar los muchos hitos que pones en vez de tratar de eliminar los hitos que posiblemente no necesites, dejando sólo los hitos que razonablemente se vayan a desarrollar dentro de la asignatura, que es lo que necesitas para superar este objetivo, va a ser difícil que el equipo de desarrollo avance. 
> 
> Como le digo tengo problemas entendiendo esto y no quiero dar más palos de ciego hasta que me quede todo claro.

Bueno, una vez más, el equipo de desarrollo te ha ayudado a estructurar mejor los diferentes hitos, aunque en ese caso, también, creo que habría que empezar por los dos hitos primeros (con sus HUs correspondientes) y el tercero dejarlo pendiente, para crearlo cuando sea necesario. Así que te sugiero que le hagas caso (y lo que yo te he comentado también, por supuesto) y tendrás este hito superado en un momento.

2021-10-07 17:04 UTC, merged